/*
 * Estados permitidos para una conversación comercial.
 */
module.exports = Object.freeze({
  IDLE: "IDLE",
  WAITING_OPERATION: "WAITING_OPERATION",
  WAITING_CUSTOMER: "WAITING_CUSTOMER",
  WAITING_PRODUCT: "WAITING_PRODUCT",
  WAITING_QUANTITY: "WAITING_QUANTITY",
  WAITING_CONFIRMATION: "WAITING_CONFIRMATION",
  PROCESSING: "PROCESSING",
  FINISHED: "FINISHED",
  CANCELLED: "CANCELLED",
});
