import { useState, useEffect, Fragment } from "react";
import { fmtFecha } from "../../utils/fecha";
import { Plus, X } from "lucide-react";
import { erpApi } from "../../services/api";
import { useServerRows } from "../../hooks/useServerStorage";

export function Beta2CheckDepositsPage(){
  const [checks,setChecks]=useState<any[]>([]),[banks]=useServerRows('afip_banks_v32',[]),[rows,setRows]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[error,setError]=useState('');
  const load=async()=>{try{const [c,d]=await Promise.all([erpApi.listChecks('EN_CARTERA'),erpApi.listDeposits()]);setChecks(c.checks||[]);setRows(d.deposits||[]);setError('')}catch(e:any){setError(e.message)}};
  useEffect(()=>{load()},[]);
  async function submit(e:any){e.preventDefault();try{await erpApi.depositChecks({banco_id:Number(editing.bancoId),cheque_ids:(editing.chequeIds||[]).map(Number),fecha:editing.fecha});setEditing(null);await load()}catch(err:any){setError(err.message)}}
  async function reconcile(id:number){try{await erpApi.reconcileDeposit(id);await load()}catch(err:any){setError(err.message)}}
  const toggle=(id:number)=>setEditing({...editing,chequeIds:(editing.chequeIds||[]).includes(id)?editing.chequeIds.filter((x:number)=>x!==id):[...(editing.chequeIds||[]),id]});
  return <div className="products-page"><div className="products-toolbar"><div><h3>Depósito de cheques</h3><p>Cartera y depósitos registrados de forma transaccional en SQLite.</p></div><button className="primary-action" onClick={()=>{if(!checks.length)return setError('No hay cheques en cartera para depositar. Registrá cheques recibidos (en la venta o en Cheques) primero.');if(!banks.length)return setError('Primero cargá un banco destino en Bancos.');setEditing({bancoId:'',chequeIds:[],fecha:new Date().toISOString().slice(0,10)})}}><Plus/> Nuevo depósito</button></div>{error&&<div className="error-box">{error}</div>}<div className="products-card"><table><thead><tr><th>Fecha</th><th>Cheques</th><th>Banco</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{fmtFecha(r.fechaDeposito)}</td><td>{(r.chequeIds||[]).length}</td><td>{banks.find((b:any)=>String(b.id)===String(r.bancoId))?.nombre||r.bancoId}</td><td className="price">$ {Number(r.importe).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>{r.estado}</td><td>{r.estado==='PENDIENTE_CONCILIACION'&&<button onClick={()=>reconcile(r.id)}>Conciliar</button>}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty-table">No hay depósitos registrados.</div>}</div>{editing&&<div className="modal-backdrop"><form className="product-modal polished-modal" onSubmit={submit}><div className="modal-head"><h3>Depositar cheques</h3><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="form-grid"><label>Banco destino<select required value={editing.bancoId} onChange={e=>setEditing({...editing,bancoId:e.target.value})}><option value="">Seleccionar...</option>{banks.map((b:any)=><option key={b.id} value={b.id}>{b.nombre}</option>)}</select></label><label>Fecha<input type="date" value={editing.fecha} onChange={e=>setEditing({...editing,fecha:e.target.value})}/></label><div className="full multi-check-selector"><strong>Cheques en cartera</strong>{checks.map(c=><label key={c.id}><input type="checkbox" checked={(editing.chequeIds||[]).includes(c.id)} onChange={()=>toggle(c.id)}/><span><b>{c.numero}</b> · {c.banco_origen||c.banco||'-'} · {c.librador||'-'}</span><em>$ {Number(c.importe).toLocaleString('es-AR',{minimumFractionDigits:2})}</em></label>)}</div></div><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="save" disabled={!(editing.chequeIds||[]).length}>Registrar depósito</button></div></form></div>}</div>
}
