import { useState, useEffect, Fragment } from "react";
import { fmtFecha } from "../../utils/fecha";
import { Plus, X } from "lucide-react";
import { erpApi } from "../../services/api";
import { useServerRows } from "../../hooks/useServerStorage";

export function Beta2PaymentOrdersPage(){
  const [suppliers]=useServerRows('afip_suppliers_v30',[]),[checks,setChecks]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[error,setError]=useState('');
  const load=async()=>{try{const [c,o]=await Promise.all([erpApi.listChecks('EN_CARTERA'),erpApi.listPaymentOrders()]);setChecks(c.checks||[]);setRows(o.orders||[]);setError('')}catch(e:any){setError(e.message)}};useEffect(()=>{load()},[]);
  const toggle=(id:number)=>setEditing({...editing,chequeIds:(editing.chequeIds||[]).includes(id)?editing.chequeIds.filter((x:number)=>x!==id):[...(editing.chequeIds||[]),id]});
  async function submit(e:any){e.preventDefault();try{await erpApi.createPaymentOrder(editing);setEditing(null);await load()}catch(err:any){setError(err.message)}}
  return <div className="products-page"><div className="products-toolbar"><div><h3>Órdenes de pago</h3><p>Pago a proveedores con efectivo, transferencia y múltiples cheques.</p></div><button className="primary-action" onClick={()=>setEditing({proveedorId:'',concepto:'',efectivo:0,transferencia:0,chequeIds:[]})}><Plus/> Nueva orden</button></div>{error&&<div className="error-box">{error}</div>}<div className="products-card"><table><thead><tr><th>Fecha</th><th>Número</th><th>Proveedor</th><th>Concepto</th><th>Cheques</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{fmtFecha(r.fecha)}</td><td><strong>{r.numero}</strong></td><td>{suppliers.find((s:any)=>String(s.id)===String(r.proveedorId))?.nombre||r.proveedorId}</td><td>{r.concepto}</td><td>{(r.chequeIds||[]).length}</td><td className="price">$ {Number(r.total).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>{r.estado}</td><td className="row-actions"><button title="Imprimir orden de pago (agente de retención)" onClick={()=>erpApi.printPaymentOrder(r.id)}>Imprimir</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-table">No hay órdenes de pago.</div>}</div>{editing&&<div className="modal-backdrop"><form className="product-modal polished-modal" onSubmit={submit}><div className="modal-head"><h3>Nueva orden de pago</h3><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="form-grid"><label className="full">Proveedor<select required value={editing.proveedorId} onChange={e=>setEditing({...editing,proveedorId:e.target.value})}><option value="">Seleccionar...</option>{suppliers.map((s:any)=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select></label><label className="full">Concepto<input required value={editing.concepto} onChange={e=>setEditing({...editing,concepto:e.target.value})}/></label><label>Efectivo<input type="number" step="any" value={editing.efectivo} onFocus={e=>e.currentTarget.select()} onChange={e=>setEditing({...editing,efectivo:Number(e.target.value)})}/></label><label>Transferencia<input type="number" step="any" value={editing.transferencia} onFocus={e=>e.currentTarget.select()} onChange={e=>setEditing({...editing,transferencia:Number(e.target.value)})}/></label><div className="full multi-check-selector"><strong>Cheques disponibles</strong>{checks.map(c=><label key={c.id}><input type="checkbox" checked={(editing.chequeIds||[]).includes(c.id)} onChange={()=>toggle(c.id)}/><span><b>{c.numero}</b> · {c.banco_origen||c.banco||'-'} · {c.librador||'-'}</span><em>$ {Number(c.importe).toLocaleString('es-AR',{minimumFractionDigits:2})}</em></label>)}{!checks.length&&<small>No hay cheques en cartera.</small>}</div></div><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="save">Emitir orden</button></div></form></div>}</div>
}
