import { useState, useEffect } from "react";
import { erpApi } from "../../services/api";
import { fmtFecha, fmtFechaHora } from "../../utils/fecha";

export function CashClosuresPage(){
  const [rows,setRows]=useState<any[]>([]); const [expanded,setExpanded]=useState<any>(null); const [pvFilter,setPvFilter]=useState(''); const [pointsOfSale,setPointsOfSale]=useState<any[]>([]); const [error,setError]=useState('');
  async function load(){try{const [r,p]=await Promise.all([erpApi.listCashSessions(),erpApi.listPointsOfSale()]);setRows(r.sessions||[]);setPointsOfSale(p.pointsOfSale||[])}catch(e:any){setError(e.message)}}
  useEffect(()=>{load()},[]);
  async function toggle(row:any){if(expanded?.session?.id===row.id){setExpanded(null);return}try{setExpanded(await erpApi.getCashSession(row.id))}catch(e:any){setError(e.message)}}
  async function close(row:any){if(!confirm(`¿Cerrar la caja #${row.id} con saldo teórico $ ${Number(row.saldo_teorico||0).toLocaleString('es-AR',{minimumFractionDigits:2})}?`))return;try{await erpApi.closeCashSession(row.id);setExpanded(null);await load()}catch(e:any){setError(e.message)}}
  const visible=rows.filter(r=>!pvFilter||Number(r.punto_venta)===Number(pvFilter));
  return <div className="products-page"><div className="products-toolbar"><div><h3>Cierres de caja</h3><p>Sesiones y movimientos persistidos en SQLite, separados por sucursal, cajero y punto de venta.</p></div></div>{error&&<div className="error-box">{error}</div>}<div className="report-filters"><label>Punto de venta<select value={pvFilter} onChange={e=>setPvFilter(e.target.value)}><option value="">Todos</option>{pointsOfSale.map((p:any)=><option key={p.id} value={p.numero}>{p.numero} · {p.nombre||`PV ${p.numero}`}</option>)}</select></label></div><div className="products-card"><table><thead><tr><th>Apertura</th><th>Cierre</th><th>PV</th><th>Sucursal</th><th>Cajero</th><th>Saldo teórico</th><th>Estado</th><th></th></tr></thead><tbody>{visible.map((r:any)=><><tr key={r.id}><td>{fmtFechaHora(r.fecha_apertura)}</td><td>{fmtFechaHora(r.fecha_cierre)}</td><td>{r.punto_venta?`PV ${String(r.punto_venta).padStart(4,'0')}`:'—'}</td><td>{r.sucursal||'Principal'}</td><td>{r.cajero||'Usuario actual'}</td><td className="price">$ {Number(r.saldo_teorico||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>{r.estado}</td><td className="inline-actions"><button onClick={()=>toggle(r)}>Detalle</button>{r.estado==='ABIERTA'&&<button onClick={()=>close(r)}>Cerrar</button>}</td></tr>{expanded?.session?.id===r.id&&<tr><td colSpan={8}><div className="cash-detail"><div className="stats-grid">{Object.entries(expanded.paymentSummary||{}).map(([k,v]:any)=><div><span>{k}</span><strong>$ {Number(v).toLocaleString('es-AR',{minimumFractionDigits:2})}</strong></div>)}</div><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Concepto</th><th>Cliente</th><th>Importe</th></tr></thead><tbody>{(expanded.movements||[]).map((m:any)=><tr key={m.id}><td>{fmtFechaHora(m.created_at)}</td><td>{m.tipo}</td><td>{m.concepto}</td><td>{m.cliente_nombre||'-'}</td><td>$ {Number(m.importe).toLocaleString('es-AR',{minimumFractionDigits:2})}</td></tr>)}</tbody></table></div></td></tr>}</>)}</tbody></table>{!visible.length&&<div className="empty-table">Todavía no hay sesiones de caja.</div>}</div></div>
}
