import { useState } from "react";
import { fmtFecha } from "../../utils/fecha";
import { Plus, Search, X } from "lucide-react";
import { useServerRows } from "../../hooks/useServerStorage";

export function ChecksPage(){
  const [banks]=useServerRows('afip_banks_v32',[{id:1,nombre:'Banco Nación'}]);
  const [rows,saveRows]=useServerRows('afip_checks_v30',[]); const [q,setQ]=useState(''); const [editing,setEditing]=useState<any>(null);
  function save(e:any){e.preventDefault();const next=editing.id?rows.map(r=>r.id===editing.id?editing:r):[{...editing,id:Date.now(),estado:'EN_CARTERA'},...rows];saveRows(next);setEditing(null)}
  function state(id:number,estado:string){saveRows(rows.map(r=>r.id===id?{...r,estado}:r))}
  const filtered=rows.filter(r=>`${r.numero} ${r.banco} ${r.librador}`.toLowerCase().includes(q.toLowerCase()));
  return <div className="products-page"><div className="products-toolbar"><div className="search-box"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar número, banco o librador..."/></div><button className="primary-action" onClick={()=>setEditing({numero:'',bancoId:banks[0]?.id||'',banco:banks[0]?.nombre||'',librador:'',importe:0,vencimiento:new Date().toISOString().slice(0,10)})}><Plus/> Nuevo cheque</button></div><div className="products-card"><table><thead><tr><th>Número</th><th>Banco</th><th>Librador</th><th>Vencimiento</th><th>Importe</th><th>Estado</th><th>Recorrido</th><th></th></tr></thead><tbody>{filtered.map(r=>{const recorrido=r.proveedor_nombre&&r.orden_pago_numero?`Entregado a ${r.proveedor_nombre} · Orden de pago OP-${String(r.orden_pago_numero).padStart(8,'0')}`:r.deposito_banco?`Depositado en ${r.deposito_banco}${r.fecha_deposito_registro?` (${fmtFecha(r.fecha_deposito_registro)})`:''}`:r.cliente_nombre?`Recibido de ${r.cliente_nombre}`:r.estado==='COBRADO'?'Cobrado (conciliado)':'En cartera';return <tr key={r.id}><td><strong>{r.numero}</strong></td><td>{r.banco}</td><td>{r.librador}</td><td>{fmtFecha(r.vencimiento)}</td><td className="price">$ {Number(r.importe).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>{r.estado}</td><td className="cheque-recorrido">{recorrido}</td><td><select value={r.estado} onChange={e=>state(r.id,e.target.value)}><option>EN_CARTERA</option><option>DEPOSITADO</option><option>COBRADO</option><option>RECHAZADO</option><option>ENTREGADO</option></select></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty-table">No hay cheques cargados.</div>}</div>{editing&&<div className="modal-backdrop"><form className="product-modal" onSubmit={save}><div className="modal-head"><h3>Nuevo cheque</h3><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="form-grid"><label>Número<input required value={editing.numero} onChange={e=>setEditing({...editing,numero:e.target.value})}/></label><label>Banco<select value={editing.bancoId||''} onChange={e=>{const id=Number(e.target.value);setEditing({...editing,bancoId:id,banco:banks.find((b:any)=>b.id===id)?.nombre||''})}}><option value="">Seleccionar banco...</option>{banks.map((b:any)=><option key={b.id} value={b.id}>{b.nombre}</option>)}</select></label><label className="full">Librador<input value={editing.librador} onChange={e=>setEditing({...editing,librador:e.target.value})}/></label><label>Importe<input type="number" value={editing.importe} onChange={e=>setEditing({...editing,importe:Number(e.target.value)})}/></label><label>Vencimiento<input type="date" value={editing.vencimiento} onChange={e=>setEditing({...editing,vencimiento:e.target.value})}/></label></div><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="save">Guardar</button></div></form></div>}</div>
}
