import React, { useState, useEffect } from "react";
import { Plus, Pencil, Trash2, Search, Save, X } from "lucide-react";
import { api } from "../../services/api";
import { Client } from "../../types";

export function ClientsPage() {
  const [pagi, setPagi] = useState(1);
  const PAGE_SIZE = 50;
  const [clients, setClients] = useState<Client[]>([]);
  const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<Client | null>(null);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [padronBusy, setPadronBusy] = useState(false);
  const [padronMsg, setPadronMsg] = useState("");
  function notify(msg:string){setSuccess(msg);setTimeout(()=>setSuccess(""),5000)}
  async function consultarPadron(){ if(!editing)return; const doc=(editing.cuit||'').replace(/\D/g,''); if(doc.length!==11){setPadronMsg('Ingresá un CUIT de 11 dígitos para consultar el padrón.');return} setPadronBusy(true);setPadronMsg('Consultando padrón ARCA…'); try{const r=await api.consultarPadron(doc);const g=r.persona?.datosGenerales||{};const dir=Array.isArray(g.domicilioFiscal)?g.domicilioFiscal[0]:g.domicilioFiscal;const nombre=g.razonSocial||`${g.nombre||''} ${g.apellido||''}`.trim()||'';const cond=(r.persona?.datosMonotributo?'MONOTRIBUTO':g.idPersona?'RESPONSABLE INSCRIPTO':null);setEditing({...editing,cuit:doc,razonSocial:nombre||editing.razonSocial||'',condicionIVA:cond||editing.condicionIVA||'CONSUMIDOR FINAL',domicilio:dir?.direccion||editing.domicilio||''});setPadronMsg(nombre?`Datos de ${nombre} cargados desde el padrón ARCA.`:'CUIT válido. Completá los datos faltantes.')}catch(err:any){setPadronMsg(`Padrón no disponible: ${err.message||'sin conexión con ARCA'}`)}finally{setPadronBusy(false)} }

  async function load(q = query) { try { setError(""); const result = await api.listClients(q); setClients(result.clientes || []); } catch (err: any) { setError(err.message); } }
  useEffect(() => { load(""); }, []);
  async function save(e: React.FormEvent) { e.preventDefault(); if (!editing) return; try { const r:any = editing.id ? await api.updateClient(editing.id, editing) : await api.createClient(editing); const c:any = r?.cliente; if(c?.yaExistia){notify(`Ya existía el cliente "${c.razonSocial}" con ese documento; se actualizaron sus datos.`)}else{notify(editing.id?'Cliente actualizado.':'Cliente creado.')} setEditing(null); await load(""); } catch (err:any) { setError(err.message); } }
  async function remove(c:Client) { if(!c.id || !window.confirm(`¿Eliminar a ${c.razonSocial}?`)) return; try { await api.deleteClient(c.id); notify('Cliente eliminado.'); await load(""); } catch(err:any){ setError(err.message); } }

  return <div className="products-page">
    <div className="products-toolbar"><div className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Buscar cliente por nombre, CUIT o teléfono"/><button onClick={()=>load()}>Buscar</button></div><button className="primary-action" onClick={()=>setEditing({razonSocial:"", condicionIVA:"CONSUMIDOR FINAL"})}><Plus size={18}/> Nuevo cliente</button></div>
    {error && <div className="error-box">{error}</div>}
    {success && <div className="success-box">{success}</div>}
    <div className="products-card"><table><thead><tr><th>Cliente</th><th>Documento</th><th>IVA</th><th>Teléfono</th><th>Email</th><th>Descuento</th><th></th></tr></thead><tbody>{clients.slice((pagi-1)*PAGE_SIZE, pagi*PAGE_SIZE).map(c=><tr key={c.id}><td><strong>{c.razonSocial}</strong><small>{c.domicilio || ''}</small></td><td>{c.cuit || c.dni || '-'}</td><td>{c.condicionIVA || '-'}</td><td>{c.telefono || '-'}</td><td>{c.email || '-'}</td><td>{Number(c.descuento||0).toLocaleString('es-AR',{maximumFractionDigits:2})} %</td><td className="row-actions"><button onClick={()=>setEditing({...c})}><Pencil size={16}/></button><button onClick={()=>remove(c)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{clients.length>PAGE_SIZE&&<div className="paginador"><button disabled={pagi<=1} onClick={()=>setPagi(p=>p-1)}>← Anterior</button><span>Página {pagi} de {Math.max(1,Math.ceil(clients.length/PAGE_SIZE))} · {clients.length} clientes</span><button disabled={pagi>=Math.ceil(clients.length/PAGE_SIZE)} onClick={()=>setPagi(p=>p+1)}>Siguiente →</button></div>}{!clients.length&&<div className="empty-table">No hay clientes para mostrar.</div>}</div>
    {editing && <div className="modal-backdrop"><form className="product-modal" onSubmit={save}><div className="modal-head"><div><h3>{editing.id?'Editar cliente':'Nuevo cliente'}</h3><p>Disponible para POS, asistente web, n8n y WhatsApp.</p></div><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="form-grid"><label className="full">Razón social<input required value={editing.razonSocial} onChange={e=>setEditing({...editing,razonSocial:e.target.value})}/></label><label>CUIT<input value={editing.cuit||''} onChange={e=>setEditing({...editing,cuit:e.target.value})}/><div className="padron-actions"><button type="button" className="padron-btn" disabled={padronBusy} onClick={consultarPadron}>{padronBusy?'Consultando…':'Consultar padrón ARCA'}</button>{padronMsg&&<small className="padron-msg">{padronMsg}</small>}</div></label><label>DNI<input value={editing.dni||''} onChange={e=>setEditing({...editing,dni:e.target.value})}/></label><label>Condición IVA<select value={editing.condicionIVA||''} onChange={e=>setEditing({...editing,condicionIVA:e.target.value})}><option>CONSUMIDOR FINAL</option><option>RESPONSABLE INSCRIPTO</option><option>MONOTRIBUTO</option><option>EXENTO</option></select></label><label>Teléfono<input value={editing.telefono||''} onChange={e=>setEditing({...editing,telefono:e.target.value})}/></label><label className="full">Domicilio<input value={editing.domicilio||''} onChange={e=>setEditing({...editing,domicilio:e.target.value})}/></label><label>Email<input type="email" value={editing.email||''} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><label>Descuento habitual %<input type="number" min="0" max="100" step="0.01" value={editing.descuento||0} onChange={e=>setEditing({...editing,descuento:Number(e.target.value)})}/></label></div><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="save" type="submit"><Save size={17}/> Guardar</button></div></form></div>}
  </div>;
}
