import { useState, useEffect } from "react";
import { MessageSquareText, PackageSearch, ShoppingCart, Users, Receipt, Warehouse, BadgeDollarSign } from "lucide-react";
import { api } from "../../services/api";

export function DashboardPage({onNavigate}:{onNavigate:(page:string)=>void}){
  const [data,setData]=useState<any>({products:[],clients:[],stock:[],documents:[]});
  const [error,setError]=useState("");
  useEffect(()=>{Promise.all([api.listProducts(""),api.listClients(""),api.listStock(),api.listDocuments("")]).then(([p,c,s,d])=>setData({products:p.products||[],clients:c.clients||[],stock:s.stock||[],documents:d.documents||d.documentos||[]})).catch((e:any)=>setError(e.message))},[]);
  const alerts=(data.stock||[]).filter((r:any)=>Boolean(r.alerta_stock)||Number(r.disponible??r.cantidad??0)<=Number(r.stock_minimo||0));
  const recent=(data.documents||[]).slice(0,5);
  const totalDocs=(data.documents||[]).reduce((sum:number,d:any)=>sum+Number(d.importe_total??d.total??0),0);
  return <div className="dashboard-page">{error&&<div className="error-box">{error}</div>}<div className="dashboard-cards"><button onClick={()=>onNavigate("products")}><PackageSearch/><span>Productos activos</span><strong>{data.products.length}</strong></button><button onClick={()=>onNavigate("clients")}><Users/><span>Clientes</span><strong>{data.clients.length}</strong></button><button className={alerts.length?"warning":""} onClick={()=>onNavigate("stock")}><Warehouse/><span>Alertas de stock</span><strong>{alerts.length}</strong></button><button onClick={()=>onNavigate("documents")}><Receipt/><span>Total documentos</span><strong>$ {totalDocs.toLocaleString("es-AR",{maximumFractionDigits:0})}</strong></button></div><div className="dashboard-grid"><section><div className="dashboard-head"><div><h3>Alertas de inventario</h3><p>Productos sin stock o por debajo del mínimo.</p></div><button onClick={()=>onNavigate("stock")}>Ver inventario</button></div>{alerts.length?<div className="dashboard-list">{alerts.slice(0,8).map((r:any,i:number)=><article key={r.id||i}><div><strong>{r.descripcion||`Producto #${r.producto_id}`}</strong><span>{r.codigo||"Sin código"}</span></div><b>{Number(r.disponible??r.cantidad??0).toLocaleString("es-AR")}</b></article>)}</div>:<div className="dashboard-empty">No hay alertas de stock.</div>}</section><section><div className="dashboard-head"><div><h3>Documentos recientes</h3><p>Últimas operaciones del chat, POS y WhatsApp.</p></div><button onClick={()=>onNavigate("documents")}>Ver todos</button></div>{recent.length?<div className="dashboard-list">{recent.map((d:any,i:number)=><article key={d.id||i}><div><strong>{d.tipo||d.tipo_documento||"DOCUMENTO"} {String(d.punto_venta||1).padStart(4,"0")}-{String(d.numero||0).padStart(8,"0")}</strong><span>{d.estado||"BORRADOR"}</span></div><b>$ {Number(d.importe_total??d.total??0).toLocaleString("es-AR",{minimumFractionDigits:2})}</b></article>)}</div>:<div className="dashboard-empty">Todavía no hay documentos.</div>}</section></div><div className="quick-module-row"><button onClick={()=>onNavigate("chat")}><MessageSquareText/><span><strong>Nueva operación</strong><small>Facturar conversando</small></span></button><button onClick={()=>onNavigate("pos")}><ShoppingCart/><span><strong>Abrir POS</strong><small>Venta rápida</small></span></button><button onClick={()=>onNavigate("accounts")}><BadgeDollarSign/><span><strong>Cuentas corrientes</strong><small>Consultar y cobrar</small></span></button></div></div>
}
