import { CircleDollarSign, FileText, Users, History, Receipt, Warehouse, Boxes, Landmark, WalletCards, FileSpreadsheet, Settings, Truck, BarChart3, ClipboardList, BadgeDollarSign, CalendarDays, Building } from "lucide-react";

export function ModulePreview({page}:{page:string}) {
  const info:any={
    sales:["Historial de ventas","Consulta, filtros y reapertura de comprobantes.",History],documents:["Comprobantes","Facturas, notas, remitos y documentos relacionados.",Receipt],budgets:["Presupuestos","Presupuestos generados desde el POS o el asistente.",FileText],"sales-notes":["Notas de venta","Seguimiento de pedidos comerciales.",ClipboardList],reservations:["Reservas","Productos reservados y fechas de entrega.",CalendarDays],stock:["Inventario","Stock por depósito y sucursal.",Warehouse],"stock-moves":["Movimientos de stock","Entradas, salidas y transferencias.",Boxes],clients:["Clientes","Clientes, condición fiscal y cuenta corriente.",Users],suppliers:["Proveedores","Proveedores, compras y saldos.",Truck],cash:["Caja","Apertura, movimientos y cierre de caja.",CircleDollarSign],accounts:["Cuentas clientes","Saldos, cobros y movimientos.",BadgeDollarSign],checks:["Cheques","Cartera de cheques y vencimientos.",FileSpreadsheet],cards:["Liquidación tarjetas","Cupones, acreditaciones y comisiones.",WalletCards],banks:["Conciliación bancaria","Movimientos bancarios y conciliación.",Landmark],reports:["Reportes","Ventas, rentabilidad e indicadores.",BarChart3],company:["Empresa","Datos fiscales, puntos de venta y certificados.",Building],settings:["Configuración","Preferencias generales del sistema.",Settings]
  };
  const [title,desc,Icon]=info[page]||["Módulo","Próximamente disponible.",Settings];
  return <div className="module-preview"><div className="module-hero"><div className="module-icon"><Icon/></div><div><span>PRÓXIMA ETAPA</span><h2>{title}</h2><p>{desc}</p></div><b>En preparación</b></div><div className="preview-cards"><div><strong>Interfaz integrada</strong><p>Conservará el estilo del segundo sistema y usará el mismo backend central.</p></div><div><strong>Datos compartidos</strong><p>Web, chat y WhatsApp consultarán la misma información.</p></div><div><strong>Control de permisos</strong><p>Usuarios, sucursales y acciones quedarán auditados.</p></div></div></div>
}
