import { useState, useEffect } from "react";
import { FileText, Search, Download } from "lucide-react";
import { api, erpApi } from "../../services/api";

export function ReceiptsPage(){
  const [rows,setRows]=useState<any[]>([]); const [q,setQ]=useState(""); const [pv,setPv]=useState(""); const [pointsOfSale,setPointsOfSale]=useState<any[]>([]); const [error,setError]=useState("");
  async function load(){try{const r=await api.listReceipts();setRows(r.recibos||[])}catch(e:any){setError(e.message)}}
  useEffect(()=>{load()},[]);
  useEffect(()=>{erpApi.listPointsOfSale().then(r=>setPointsOfSale(r.pointsOfSale||[])).catch(()=>{})},[]);
  const filtered=rows.filter(r=>(!pv||Number(r.punto_venta)===Number(pv))&&`${r.cliente_nombre} ${r.cliente_doc} ${r.numero}`.toLowerCase().includes(q.toLowerCase()));
  function csv(){const lines=[["Fecha","Numero","Punto de venta","Cliente","Documento","Estado","Total"],...filtered.map(r=>[r.created_at,`${r.punto_venta}-${r.numero}`,r.punto_venta,r.cliente_nombre,r.cliente_doc,r.estado,r.importe_total])];const blob=new Blob([lines.map(x=>x.join(';')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='recibos.csv';a.click()}
  async function pdf(r:any){try{await api.downloadReceiptPdf(r.id,`recibo-${String(r.punto_venta).padStart(4,'0')}-${String(r.numero).padStart(8,'0')}.pdf`)}catch(e:any){setError(e.message)}}
  return <div className="products-page"><div className="products-toolbar"><div><h3>Recibos de cobro</h3><p>Cobros generados desde cuenta corriente, separados por punto de venta (cada recibo se imprime con el logo de su PV).</p></div><div className="toolbar-actions"><button onClick={csv}><Download/> Excel/CSV</button></div></div><div className="search-box"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por cliente, documento o número..."/><label className="pv-filter-label">Punto de venta<select value={pv} onChange={e=>setPv(e.target.value)}><option value="">Todos</option>{pointsOfSale.map((p:any)=><option key={p.id} value={p.numero}>{p.numero} · {p.nombre||`PV ${p.numero}`}</option>)}</select></label></div>{error&&<div className="error-box">{error}</div>}<div className="products-card"><table><thead><tr><th>Fecha</th><th>Número</th><th>PV</th><th>Cliente</th><th>Documento</th><th>Estado</th><th>Total</th><th>Medios</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('es-AR')}</td><td><strong>{String(r.punto_venta).padStart(4,'0')}-{String(r.numero).padStart(8,'0')}</strong></td><td>PV {String(r.punto_venta||1).padStart(4,'0')}</td><td>{r.cliente_nombre}</td><td>{r.cliente_doc}</td><td>{r.estado}</td><td className="price">$ {Number(r.importe_total).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>{(r.detalles||[]).map((d:any)=>d.medio_pago).join(', ')||'-'}</td><td><button onClick={()=>pdf(r)}><FileText size={16}/> PDF</button></td></tr>)}</tbody></table></div></div>
}
