import { useState, useEffect, Fragment } from "react";
import { fmtFecha } from "../../utils/fecha";
import { Plus, X } from "lucide-react";
import { api, erpApi } from "../../services/api";
import { SearchableClientSelect } from "../shared/SearchableClientSelect";
import { MoneyInput } from "../shared/MoneyInput";

export function ReserveFundsPage(){
 const [clients,setClients]=useState<any[]>([]);const [rows,setRows]=useState<any[]>([]);const [editing,setEditing]=useState<any>(null);const [error,setError]=useState('');async function load(){try{const [c,r]=await Promise.all([api.listClients(''),erpApi.listReserveFunds()]);setClients(c.clientes||[]);setRows(r.reservations||[])}catch(e:any){setError(e.message)}}useEffect(()=>{load()},[]);async function submit(e:any){e.preventDefault();try{await erpApi.createReserveFund({cliente_id:Number(editing.clienteId),importe_original:Number(editing.importe),fecha:new Date().toISOString().slice(0,10),lista_precio_nombre:'GENERAL',observaciones:editing.observaciones});setEditing(null);load()}catch(err:any){setError(err.message)}}return <div className="products-page"><div className="products-toolbar"><div><h3>Reservas por monto</h3><p>Conserva el saldo entregado y congela los precios vigentes del catálogo.</p></div><button className="primary-action" onClick={()=>setEditing({clienteId:'',importe:0,observaciones:''})}><Plus/> Nueva reserva</button></div>{error&&<div className="error-box">{error}</div>}<div className="products-card"><table><thead><tr><th>Número</th><th>Fecha</th><th>Cliente</th><th>Monto original</th><th>Saldo</th><th>Lista</th><th>Estado</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><strong>{r.numero}</strong></td><td>{fmtFecha(r.fecha)}</td><td>{r.cliente}</td><td>$ {Number(r.importe_original).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td className="price">$ {Number(r.saldo).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>{r.lista_precio_nombre}</td><td>{r.estado}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty-table">No hay reservas por monto.</div>}</div>{editing&&<div className="modal-backdrop"><form className="product-modal polished-modal" onSubmit={submit}><div className="modal-head"><h3>Nueva reserva por monto</h3><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="form-grid"><label className="full">Cliente<SearchableClientSelect clients={clients} value={editing.clienteId} onChange={id=>setEditing({...editing,clienteId:id})}/></label><label>Importe entregado<MoneyInput value={editing.importe} onChange={v=>setEditing({...editing,importe:v})}/></label><label className="full">Observaciones<input value={editing.observaciones} onChange={e=>setEditing({...editing,observaciones:e.target.value})}/></label></div><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="save">Registrar reserva</button></div></form></div>}</div>}
