import React, { useState, useEffect } from "react";
import { Plus, Save, Minus, X, Warehouse } from "lucide-react";
import { api } from "../../services/api";
import { SearchableProductSelect } from "../shared/SearchableProductSelect";
import { Product } from "../../types";

export function StockPage() {
  const [stock,setStock]=useState<any[]>([]); const [products,setProducts]=useState<Product[]>([]); const [error,setError]=useState(""); const [movement,setMovement]=useState<any>(null);
  async function load(){try{setError("");const [s,p]=await Promise.all([api.listStock(),api.listProducts("")]);setStock(s.stock||[]);setProducts(p.products||[])}catch(e:any){setError(e.message)}}
  useEffect(()=>{load()},[]);
  async function saveMovement(e:React.FormEvent){e.preventDefault();try{const payload={productoId:Number(movement.productoId),cantidad:Number(movement.cantidad),motivo:movement.motivo};movement.tipo==='ENTRADA'?await api.stockEntry(payload):await api.stockExit(payload);setMovement(null);await load()}catch(e:any){setError(e.message)}}
  const alerts=stock.filter((s:any)=>Boolean(s.alerta_stock)||Number(s.disponible??s.cantidad??0)<=Number(s.stock_minimo||0));
  return <div className="products-page"><div className="products-toolbar"><div><h3>Inventario actual</h3><p>Stock compartido por POS, facturación, asistente y WhatsApp.</p></div><div className="inline-actions"><button className="primary-action" onClick={()=>setMovement({tipo:'ENTRADA',productoId:'',cantidad:1,motivo:'Entrada manual'})}><Plus size={18}/> Entrada</button><button className="primary-action secondary" onClick={()=>setMovement({tipo:'SALIDA',productoId:'',cantidad:1,motivo:'Salida manual'})}><Minus size={18}/> Salida</button></div></div>{alerts.length>0&&<div className="stock-alert-banner"><Warehouse size={20}/><div><strong>{alerts.length} producto(s) requieren atención</strong><span>Están sin stock o por debajo del mínimo configurado.</span></div></div>}{error&&<div className="error-box">{error}</div>}<div className="products-card"><table><thead><tr><th>Producto</th><th>Depósito</th><th>Actual</th><th>Mínimo</th><th>Reservado</th><th>Estado</th></tr></thead><tbody>{stock.map((r:any,i:number)=>{const alert=Boolean(r.alerta_stock)||Number(r.disponible??r.cantidad??0)<=Number(r.stock_minimo||0);return <tr key={r.id||i} className={alert?'stock-row-alert':''}><td><strong>{r.descripcion||`Producto #${r.producto_id}`}</strong><small>{r.codigo||''}</small></td><td>{r.deposito||'Principal'}</td><td className="price">{Number(r.disponible??r.cantidad??0).toLocaleString('es-AR')}</td><td>{Number(r.stock_minimo||0).toLocaleString('es-AR')}</td><td>{Number(r.reservado||0).toLocaleString('es-AR')}</td><td><span className={alert?'badge danger':'badge success'}>{alert?'REPOSICIÓN':'NORMAL'}</span></td></tr>})}</tbody></table>{!stock.length&&<div className="empty-table">Todavía no hay stock registrado.</div>}</div>{movement&&<div className="modal-backdrop"><form className="product-modal stock-modal" onSubmit={saveMovement}><div className="modal-head"><div><h3>{movement.tipo==='ENTRADA'?'Entrada':'Salida'} de stock</h3><p>Buscá el producto sin necesidad de conocer su ID.</p></div><button type="button" onClick={()=>setMovement(null)}><X/></button></div><div className="form-grid"><label className="full">Producto<SearchableProductSelect products={products} value={movement.productoId} onChange={id=>setMovement({...movement,productoId:id})}/></label><label>Cantidad<input min="0.001" step="0.001" type="number" value={movement.cantidad} onChange={e=>setMovement({...movement,cantidad:e.target.value})}/></label><label className="full">Motivo<input value={movement.motivo} onChange={e=>setMovement({...movement,motivo:e.target.value})}/></label></div><div className="modal-actions"><button type="button" onClick={()=>setMovement(null)}>Cancelar</button><button className="save" type="submit" disabled={!movement.productoId}><Save size={17}/> Registrar</button></div></form></div>}</div>
}
