import { useState } from "react";
import { Plus, Pencil, Search, X } from "lucide-react";
import { useServerRows } from "../../hooks/useServerStorage";

export function SuppliersPage(){
  const [rows,saveRows]=useServerRows('afip_suppliers_v30',[]); const [q,setQ]=useState(''); const [editing,setEditing]=useState<any>(null);
  function save(e:any){e.preventDefault();const next=editing.id?rows.map(r=>r.id===editing.id?editing:r):[{...editing,id:Date.now()},...rows];saveRows(next);setEditing(null)}
  const filtered=rows.filter(r=>`${r.nombre} ${r.cuit} ${r.telefono}`.toLowerCase().includes(q.toLowerCase()));
  return <div className="products-page"><div className="products-toolbar"><div className="search-box"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar proveedor..."/></div><button className="primary-action" onClick={()=>setEditing({nombre:'',cuit:'',telefono:'',email:'',saldo:0})}><Plus/> Nuevo proveedor</button></div><div className="products-card"><table><thead><tr><th>Proveedor</th><th>CUIT</th><th>Teléfono</th><th>Email</th><th>Saldo</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.nombre}</strong></td><td>{r.cuit}</td><td>{r.telefono}</td><td>{r.email}</td><td className="price">$ {Number(r.saldo||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td><button onClick={()=>setEditing({...r})}><Pencil size={16}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-table">No hay proveedores cargados.</div>}</div>{editing&&<div className="modal-backdrop"><form className="product-modal" onSubmit={save}><div className="modal-head"><h3>Proveedor</h3><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="form-grid"><label className="full">Razón social<input required value={editing.nombre} onChange={e=>setEditing({...editing,nombre:e.target.value})}/></label><label>CUIT<input value={editing.cuit} onChange={e=>setEditing({...editing,cuit:e.target.value})}/></label><label>Teléfono<input value={editing.telefono} onChange={e=>setEditing({...editing,telefono:e.target.value})}/></label><label>Email<input value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><label>Saldo inicial<input type="number" value={editing.saldo} onChange={e=>setEditing({...editing,saldo:Number(e.target.value)})}/></label></div><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="save">Guardar</button></div></form></div>}</div>
}
