import { useState, useEffect, Fragment } from "react";
import { fmtFecha } from "../../utils/fecha";
import { Check, Printer } from "lucide-react";
import { erpApi } from "../../services/api";

export function VatBooksPage(){
 const now=new Date();const [tab,setTab]=useState<'VENTAS'|'COMPRAS'>('VENTAS');const [month,setMonth]=useState(now.getMonth()+1);const [year,setYear]=useState(now.getFullYear());const [pv,setPv]=useState(0);const [pointsOfSale,setPointsOfSale]=useState<any[]>([]);const [data,setData]=useState<any>({sales:[],purchases:[],summary:{debit:0,credit:0,balance:0},empresa:{}});const [error,setError]=useState('');
 async function load(){try{setData(await erpApi.getVatBook(month,year,pv||undefined))}catch(e:any){setError(e.message)}}useEffect(()=>{load()},[month,year,pv]);useEffect(()=>{erpApi.listPointsOfSale().then(r=>setPointsOfSale(r.pointsOfSale||[])).catch(()=>{})},[]);const rows=tab==='VENTAS'?data.sales||[]:data.purchases||[];
 function printBook(){const nombreEmpresa=data.empresa?.razonSocial||'';const pvLabel=pv?`${String(pv).padStart(4,'0')}${pointsOfSale.find((p:any)=>Number(p.numero)===pv)?.nombre?` · ${pointsOfSale.find((p:any)=>Number(p.numero)===pv).nombre}`:''}`:'TODOS';const title=`Libro IVA ${tab==='VENTAS'?'Ventas':'Compras'} - ${month}/${year}`;const body=rows.map((r:any)=>`<tr><td>${fmtFecha(r.fecha)}</td><td>${r.razon_social||''}</td><td>${r.cuit||''}</td><td>${r.tipo||''} ${String(r.punto_venta||1).padStart(5,'0')}-${r.numero||''}</td><td>${Number(r.neto||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>${Number(r.iva||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>${Number(r.total||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</td></tr>`).join('');const w=window.open('','_blank');w?.document.write(`<html><head><style>@page{size:A4 landscape;margin:8mm}body{font-family:Arial;font-size:9px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aaa;padding:4px}h2{font-size:11px;color:#333}</style></head><body><h1>${title}</h1><h2>${nombreEmpresa?`Empresa: ${nombreEmpresa}`:''}${pvLabel&&tab==='VENTAS'?` · Punto de venta: ${pvLabel}`:''}</h2><table><thead><tr><th>Fecha</th><th>Razón social</th><th>CUIT</th><th>Comprobante</th><th>Neto</th><th>IVA</th><th>Total</th></tr></thead><tbody>${body}</tbody></table><h3>Débito fiscal: $ ${Number(data.summary.debit||0).toLocaleString('es-AR')} · Crédito fiscal: $ ${Number(data.summary.credit||0).toLocaleString('es-AR')} · ${Number(data.summary.balance||0)>=0?'IVA a pagar':'Saldo a favor'}: $ ${Math.abs(Number(data.summary.balance||0)).toLocaleString('es-AR')}</h3></body></html>`);w?.document.close();setTimeout(()=>w?.print(),300)}
 return <div className="products-page"><div className="products-toolbar"><div><h3>Libro IVA</h3><p>Ventas y compras fiscales consolidadas por período.</p></div><button className="primary-action" onClick={printBook}><Printer size={16}/> PDF / imprimir</button></div><div className="vat-period"><label>Mes<select value={month} onChange={e=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2026,i,1).toLocaleString('es-AR',{month:'long'}).toUpperCase()}</option>)}</select></label><label>Año<input type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></label>{tab==='VENTAS'&&<label>Punto de venta<select value={pv} onChange={e=>setPv(Number(e.target.value))}><option value={0}>TODOS</option>{pointsOfSale.map((p:any)=><option key={p.id} value={p.numero}>{p.numero} · {p.nombre||`PV ${p.numero}`}</option>)}</select></label>}<button onClick={load}><Check/> Aceptar</button></div>{error&&<div className="error-box">{error}</div>}<div className="catalog-tabs"><button className={tab==='VENTAS'?'active':''} onClick={()=>setTab('VENTAS')}>IVA Ventas</button><button className={tab==='COMPRAS'?'active':''} onClick={()=>setTab('COMPRAS')}>IVA Compras</button></div><div className="vat-summary"><div><span>Débito fiscal</span><strong>$ {Number(data.summary.debit||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</strong></div><div><span>Crédito fiscal</span><strong>$ {Number(data.summary.credit||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</strong></div><div className={Number(data.summary.balance||0)>=0?'positive':'negative'}><span>{Number(data.summary.balance||0)>=0?'IVA a pagar':'Saldo a favor'}</span><strong>$ {Math.abs(Number(data.summary.balance||0)).toLocaleString('es-AR',{minimumFractionDigits:2})}</strong></div></div><div className="products-card"><table><thead><tr><th>Fecha</th><th>Razón social</th><th>CUIT</th><th>Comprobante</th><th>Neto gravado</th><th>IVA</th><th>Total</th></tr></thead><tbody>{rows.map((r:any)=><tr key={`${tab}-${r.id}`}><td>{fmtFecha(r.fecha)}</td><td>{r.razon_social}</td><td>{r.cuit||'-'}</td><td>{r.tipo} {String(r.punto_venta||1).padStart(5,'0')}-{r.numero}</td><td>$ {Number(r.neto||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td>$ {Number(r.iva||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</td><td className="price">$ {Number(r.total||0).toLocaleString('es-AR',{minimumFractionDigits:2})}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty-table">No hay comprobantes fiscales en este período.</div>}</div></div>}
