const router=require('express').Router();
const path=require('path');
const fs=require('fs');
const multer=require('multer');
const c=require('../controllers/erpConsolidation.controller');
const beta2=require('../controllers/beta2.controller');
const uploadDir=path.join(process.cwd(),'storage','private','fiscal');
fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,`${req.empresa?.id||1}-${req.params.type}-${Date.now()}${path.extname(file.originalname).toLowerCase()}`)});
const upload=multer({storage,limits:{fileSize:1024*1024},fileFilter:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();const ok=req.params.type==='key'?['.key','.pem'].includes(ext):['.crt','.cer','.pem'].includes(ext);cb(ok?null:new Error('Formato de archivo no permitido.'),ok)}});
router.get('/state/:key',c.getAppState);router.put('/state/:key',c.saveAppState);router.delete('/state/:key',c.deleteAppState);
router.get('/app/estado',c.appEstado);router.get('/changelog',c.listChangelog);router.get('/whatsapp/conversaciones',c.listWhatsappConversations);router.patch('/whatsapp/conversaciones/:id',c.tomarConversacionWhatsapp);router.post('/whatsapp/conversaciones/:id/crear-pedido',c.crearPedidoWhatsapp);router.post('/whatsapp/conversaciones/:id/mensaje',c.enviarMensajeWhatsappTray);router.get('/whatsapp/notificaciones',c.listWhatsappNotificaciones);router.patch('/whatsapp/notificaciones/:id',c.marcarNotificacionEnviada);router.post('/whatsapp/notificaciones/:id/enviar',c.enviarNotificacionWhatsapp);router.get('/whatsapp/config',c.getWhatsappConfig);router.put('/whatsapp/config',c.saveWhatsappConfig);router.post('/whatsapp/config/probar',c.probarWhatsappConfig);router.get('/whatsapp/pedidos',c.listWhatsappPedidos);router.patch('/whatsapp/pedidos/:id/reparto',c.cambiarRepartoPedido);router.post('/whatsapp/pedidos/:id/enviar-pago',c.enviarLinkPago);router.patch('/whatsapp/notificaciones/:id/verificar-pago',c.verificarPago);router.post('/whatsapp/demo-message',c.whatsappDemoMessage);router.post('/whatsapp/demo-empleado-message',c.whatsappDemoEmpleadoMessage);router.get('/whatsapp/resumen-notificaciones',c.whatsappResumenNotificaciones);router.get('/sorteos/cupones',c.listCuponesSorteo);router.patch('/sorteos/cupones/:id',c.updateCuponSorteo);
router.get('/resources/:key',beta2.readResource);router.put('/resources/:key',beta2.writeResource);
router.get('/bancos',c.listBanks);router.post('/bancos',c.saveBank);router.put('/bancos/:id',c.saveBank);router.get('/bancos/reconciliacion',c.bankReconciliation);
router.get('/puntos-venta',c.listPos);router.post('/puntos-venta',c.savePos);router.put('/puntos-venta/:id',c.savePos);
router.get('/cheques',c.listChecks);router.post('/cheques',c.createCheck);router.post('/cheques/depositos',c.depositChecks);
router.get('/cheques/depositos/listado',beta2.listDeposits);router.post('/cheques/depositos/:id/conciliar',beta2.reconcileDeposit);
router.get('/ordenes-pago',beta2.listPaymentOrders);router.post('/ordenes-pago',beta2.createPaymentOrder);router.get('/ordenes-pago/:id/imprimir',c.printPaymentOrder);
router.get('/whatsapp-autorizados',c.listWhatsapp);router.post('/whatsapp-autorizados',c.saveWhatsapp);router.put('/whatsapp-autorizados/:id',c.saveWhatsapp);
router.get('/compras',c.listPurchases);router.post('/compras',c.savePurchase);router.delete('/compras/:id',c.deletePurchase);
router.get('/libro-iva',c.vatBook);
router.post('/precios/actualizacion-masiva',c.updatePrices);
router.get('/pos/borrador-iva',c.borradorIva);router.post('/pos/borrador-iva/ajustes',c.saveBorradorIvaAjuste);router.post('/pos/borrador-iva/rubros/:id',c.renameBorradorIvaRubro);
router.get('/reservas-monto',c.listReserveFunds);router.post('/reservas-monto',c.createReserveFund);router.post('/reservas-monto/:id/consumos',c.consumeReserveFund);
router.get('/pos/catalogos',c.listPosCatalogs);router.get('/pos/mis-puntos-venta',c.misPuntosVenta);router.put('/pos/puntos-venta/:id/logo',c.subirLogoPos);router.get('/pos/comprobantes-config',c.listPosComprobantesConfig);router.put('/pos/comprobantes-config/:tipo',c.savePosComprobanteConfig);router.get('/pos/operaciones',c.listPosOperations);router.get('/pos/operaciones/:id/items',c.listPosOperationItems);router.post('/pos/operaciones',c.createPosOperation);router.get('/pos/cobros-tarjetas',c.listCardCollections);router.get('/pos/reporte-productos',c.reporteProductos);router.get('/pos/ranking-ventas',c.rankingVentas);router.get('/cajas/sesiones',c.listCashSessions);router.get('/cajas/sesiones/:id/medios',c.listCashSessionMedios);router.get('/cajas/sesiones/:id',c.cashSessionDetail);router.post('/cajas/sesiones/:id/cerrar',c.closeCashSession);
router.post('/pos/operaciones/:id/fiscal/reintentar',c.retryFiscalCae);router.post('/pos/operaciones/:id/nota-credito',c.emitirNotaCredito);router.post('/pos/operaciones/:id/nota-debito',c.emitirNotaDebito);router.post('/pos/operaciones/:id/facturar',c.facturarPedido);router.post('/pos/operaciones/:id/anular',c.anularOperacion);
router.post('/cajas/sesiones/:id/arqueo-cerrar',beta2.closeCash);
router.post('/cajas/sesiones/abrir',beta2.openCash);router.post('/cajas/movimientos',beta2.cashMovement);
router.get('/pos/borradores',beta2.getDrafts);router.put('/pos/borradores',beta2.saveDrafts);router.delete('/pos/borradores',beta2.deleteDrafts);
router.get('/pos/operaciones/:id/imprimir',beta2.printPosOperation);router.get('/pos/operaciones/:id/imprimir-regalos',beta2.printPosVouchers);
router.get('/empresa/archivos-fiscales',c.fiscalFiles);router.post('/empresa/archivos-fiscales/:type',upload.single('file'),c.uploadFiscal);
router.get('/modulos',c.getModulosEmpresa);
router.get('/cobros-temporales',c.listCobrosTemporales);router.post('/cobros-temporales',c.createCobroTemporal);router.delete('/cobros-temporales/:id',c.deleteCobroTemporal);router.post('/cobros-temporales/enviar-cuenta-corriente',c.enviarCobrosCuentaCorriente);
module.exports=router;
