/*
 * Estados utilizados mientras un CommercialCommand
 * se completa mediante una conversación.
 */
module.exports = Object.freeze({
  WAITING_OPERATION: "WAITING_OPERATION",

  WAITING_CUSTOMER: "WAITING_CUSTOMER",

  WAITING_CUSTOMER_SELECTION: "WAITING_CUSTOMER_SELECTION",

  WAITING_PRODUCT: "WAITING_PRODUCT",

  WAITING_PRODUCT_SELECTION: "WAITING_PRODUCT_SELECTION",

  WAITING_PAYMENT: "WAITING_PAYMENT",

  WAITING_CONFIRMATION: "WAITING_CONFIRMATION",

  PROCESSING: "PROCESSING",

  COMPLETED: "COMPLETED",

  CANCELLED: "CANCELLED",
});
